CREATE DATABASE QLNV

USE QLNV

CREATE TABLE tblChucvu (
  MaCV VARCHAR(2) PRIMARY KEY,
  TenCV VARCHAR(50) NOT NULL
);

CREATE TABLE tblSinhVien (
  MaNV VARCHAR(10) PRIMARY KEY,
  MaCV VARCHAR(2) NOT NULL,
  TenNV VARCHAR(50) NOT NULL,
  NgaySinh DATE NOT NULL,
  LuongCanBan DECIMAL(18,2) NOT NULL,
  NgayCong INT NOT NULL,
  PhuCap DECIMAL(18,2) NOT NULL,
  FOREIGN KEY (MaCV) REFERENCES tblChucvu(MaCV)
);
